### ISSUE TITLE
Compiling Ranger recipe on GoboLinux 016.01 in VM fails

### ISSUE THREAD

**Issue by mraper3** [gobolinux/Recipes#19] opened 2017-05-07 18:03 UTC
I've been trying to compile the Ranger recipe on GL 016.01 in a VirtualBox VM (Win 7 host), but it fails with these messages:

"/usr/bin/env: 'python': No such file or directory
Compile: Your Scripts package is too old. Please update it by running 'InstallPackage Scripts'."

I've confirmed that I have Python 2.7 installed using the 'which' command, and I've also confirmed that I have Scripts 016.01 installed by looking in the /Programs directory. So I don't know why these errors are happening, but they are preventing the package from compiling.

Output from SystemInfo:
Kernel: Linux 4.9.16-Gobo x86_64
Compilation: #0 SMP PREEMPT Mon Mar 20 08:53:55 BRT 2017
Processor: Intel(R) Core(TM) i7-3940XM CPU @ 3.00 GHz
Memory: 16423312 kB

Output from Compile
![output_from_compile](https://cloud.githubusercontent.com/assets/5323781/25783656/8b3970c0-3325-11e7-86db-7e8627420d26.png)

I'm not sure if this is the right place to bring this up, or if I should go to the recipe maker, or the Ranger devs themselves. If you need more information, please let me know. This is preventing me from installing the recipe, so any help you can give will be much appreciated. Thanks!

**Comment by AitorATuin** [comment] 2017-05-07 18:33
can you please show the output of these commands:
```
currentver=$(bash -c "source bin/ScriptFunctions && Import GoboLinux && Get_Version Scripts Current")
echo "Current Scripts version $currentver"
GuessLatest $currentver 3.0
```

**Comment by mraper3** [comment] 2017-05-07 18:44
output from echo and GuessLatest:
Current Scripts version 016.01
016.01

**Comment by AitorATuin** [comment] 2017-05-07 19:00
Seems to be a problem when running `GetLatest` in the sandbox (python is missing for some reason). 
Which versions of python do you have installed?
What's the output of `ls -la /System/Index/bin/python`?
Are you using `Runner`?, you can know if it's available  running `Runner ls` also using `Compile Ranger -v` should tell you if you have Runner support.

**Comment by mraper3** [comment] 2017-05-07 19:06
> Seems to be a problem when running GetLatest in the sandbox (python is missing for some reason).
Which versions of python do you have installed?
What's the output of ls -la /System/Index/bin/python?
Are you using Runner?, you can know if it's available running Runner ls also using Compile Ranger -v should tell you if you have Runner support.

Output of the ls -al command is a symlink to /Programs/Python/2.7.12/bin/python.
Runner ls used in my user directory correctly gives ~/Desktop and ~/Downloads, as expected.
Compile Ranger -v gives:
Compile: Runner is available, using it.
WARNING: No packages matching requirements were found, skipping dependency Python.

**Comment by AitorATuin** [comment] 2017-05-07 19:21
I can't reproduce it here right now, I'm using git versions for Compile/Scripts so I will try to reproduce it with Compile/Scripts versions from ISO.

**Comment by mraper3** [comment] 2017-05-07 19:23
That's right, I'm installed the OS into the VM with the GoboLinux-016.01-x86_64.iso file I downloaded from the website.

**Comment by lucasvr** [comment] 2017-05-07 20:15
This problem should have been fixed on our git snapshots of Scripts/Compile. As a workaround, you can include the following line on `/Data/Compile/Recipes/Ranger/1.8.1-r1/Resources/Dependencies:`

`Python < 3.0.0`

It should build fine afterwards. Please confirm so that we can close this ticket.

I'll prepare a new version of Compile and Scripts so that users can get a formal fix for this problem in the coming week.

**Comment by mraper3** [comment] 2017-05-07 20:23
It LOOKS like Ranger built OK; I can use it as expected.  However, there was never a confirmation from Compile that it completed successfully.  The last line of output from Compile was
`SignProgram: gpg not found`
Then it went back to the prompt.

**Comment by lucasvr** [comment] 2017-05-07 20:26
If you scroll up you should see that the program has been successfully installed and symlinked. SignProgram is the very last step performed by the compile chain.
I'm closing this bug now -- thanks for reporting it in first place!

**Closed by lucasvr** 2017-05-07 20:26 UTC

**Comment by mraper3** [comment] 2017-05-07 20:29
You're right, I'm seeing the right messages above, just like you said.  And no problem about reporting the bug.  I was first attracted by the AwesomeWM-neon theme, but I stayed because I like the system and think it's got quite a bit of potential.  Thanks for continuing to work on it!  I'll pass along more bugs and such as I play around with it.

**Comment by AitorATuin** [comment] 2017-05-07 20:44
Versions shipped with ISO seems to be really old :P

**Comment by mraper3** [comment] 2017-05-07 20:47
Well, I guess that's the risk you take going with the stable versions instead of the git versions.  That said, that's all I saw on the site as far as officially available versions.  I've looked through the GoboLinux GitHub site, but there doesn't seem to be a clone-able git of the OS itself.  Probably not needed, given the SystemUpdate functions and such.

**Comment by AitorATuin** [comment] 2017-05-07 20:56
There are `git` version Recipes for Compile and Scripts so it should be easy to update those packages (the most critical ones) without any problem.

**Comment by mraper3** [comment] 2017-05-07 20:58
Cool, I'll look those up on the Recipe search page.  Alright, I'll stop wasting your time gabbing here.  Thanks again!
